version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: # Mówię Compose, żeby wczytał zmienne z tego pliku.
      - .env
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    env_file: # Tutaj również wczytuję te same zmienne.
      - .env
    environment:
      - POSTGRES_HOST=db # Tę zmienną zostawiam, bo jest specyficzna dla Dockera, a nie jest sekretem.
    depends_on:
      - db

volumes:
  postgres_data: